CREATE TABLE IF NOT EXISTS `T_CERTIFICATE` (
  `ca_id` VARCHAR(36) NOT NULL,
  `serial` INT UNSIGNED NOT NULL DEFAULT '0',
  `common_name` VARCHAR(255) NOT NULL DEFAULT '',
  `private_key` TEXT NOT NULL DEFAULT '',
  `cert_type` VARCHAR(10) NOT NULL DEFAULT 'UNKNOWN',
  `cert_data` TEXT NOT NULL DEFAULT '',
  `created` VARCHAR(19) NOT NULL DEFAULT '1970-01-01T09:00:00',
  `expiration_date` VARCHAR(19) NOT NULL DEFAULT '1970-01-01T09:00:00',
  `is_revoked` BIT(1) NOT NULL DEFAULT b'0',
  `revoked` VARCHAR(19) NOT NULL DEFAULT '1970-01-01T09:00:00',
  PRIMARY KEY(`ca_id`, `serial`),
  FOREIGN KEY (`cert_type`) REFERENCES M_CERT_TYPE(`cert_type`)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;