CREATE TABLE IF NOT EXISTS `M_CERT_TYPE` (
  `cert_type` VARCHAR(10) NOT NULL PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO M_CERT_TYPE(`cert_type`) VALUES
  ('UNKNOWN'),
  ('CA'),
  ('SERVER'),
  ('CLIENT');